import streamlit as st
from supabase import create_client

# Connect to Supabase using secrets.toml
url = st.secrets["supabase"]["url"]
key = st.secrets["supabase"]["key"]
supabase = create_client(url, key)

# Complete Master Taxonomy Dataset
initial_data = [
    {"category": "Interviews", "subcategory": None, "topic": "Podcast", "tonality": "All Tonalities"},
    {"category": "Interviews", "subcategory": None, "topic": "Interviews", "tonality": "All Tonalities"},
    {"category": "Event", "subcategory": None, "topic": "Inauguration", "tonality": "All Tonalities"},
    {"category": "Event", "subcategory": None, "topic": "Foundation Stone", "tonality": "All Tonalities"},
    {"category": "Event", "subcategory": None, "topic": "Inspection", "tonality": "All Tonalities"},
    {"category": "Event", "subcategory": None, "topic": "Review Meeting", "tonality": "All Tonalities"},
    {"category": "Event", "subcategory": None, "topic": "Traffic Management", "tonality": "Only Positive"},
    {"category": "Event", "subcategory": None, "topic": "Road Safety Measures", "tonality": "Only Positive"},
    {"category": "Event", "subcategory": None, "topic": "Road Safety Committee Meeting", "tonality": "All Tonalities"},
    {"category": "Event", "subcategory": None, "topic": "NHAI Personnel", "tonality": "All Tonalities"},
    {"category": "Event", "subcategory": None, "topic": "Citizen-Centric Initiatives", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Construction Delay", "topic": "Construction Delay", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Land Acquisition Issues", "topic": "Land Acquisition", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Land Acquisition Issues", "topic": "Land Acquisition Issues", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Road Conditions", "topic": "Broken Drains", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Road Conditions", "topic": "Broken Grills & Dividers", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Road Conditions", "topic": "Damaged Roads", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Road Conditions", "topic": "Road Damage", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Road Conditions", "topic": "Dust Issues", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Road Conditions", "topic": "Illegal Cuts", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Road Conditions", "topic": "Potholes", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Road Conditions", "topic": "Bad Roads", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Water Logging", "topic": "Water Logging", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Water Logging", "topic": "Drainage Issue", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Lack of Maintenance", "topic": "Sapling Issues", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Lack of Maintenance", "topic": "Improper Lanes", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Lack of Maintenance", "topic": "Reflector Issues", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Lack of Maintenance", "topic": "Deep Curve Reflector Issues", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Lack of Maintenance", "topic": "Street Issues", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Lack of Maintenance", "topic": "Highway Restoration", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Encroachment and Legal Issues", "topic": "Advertising & Signage Encroachments", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Encroachment and Legal Issues", "topic": "Agments", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Encroachment and Legal Issues", "topic": "Illegal Parking", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Encroachment and Legal Issues", "topic": "Cultural Encroachments", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Encroachment and Legal Issues", "topic": "Construction-Related Encroachment", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Encroachment and Legal Issues", "topic": "Encroachment by Roadside Houses", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Encroachment and Legal Issues", "topic": "Encroachment by Shopkeepers", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Encroachment and Legal Issues", "topic": "Court Notices to NHAI", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Encroachment and Legal Issues", "topic": "Illegal Hoarding", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Encroachment and Legal Issues", "topic": "Parking-Related Encroachments", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Encroachment and Legal Issues", "topic": "Religious Structure", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Encroachment and Legal Issues", "topic": "Structural / Permanent Encroachments", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Encroachment and Legal Issues", "topic": "Temporary / Commercial Encroachments", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Encroachment and Legal Issues", "topic": "Accidents due to Illegal Parking", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Toll Issues", "topic": "FASTag Issues", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Toll Issues", "topic": "Extra Money Deduction", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Toll Issues", "topic": "Misbehavior of Toll Staff", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Toll Issues", "topic": "Multiple Toll Plazas Within 60 km", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Toll Issues", "topic": "Overcharging", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Toll Issues", "topic": "Toll Issues", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Toll Issues", "topic": "Toll Pricing", "tonality": "Neutral & Negative"},
    {"category": "Grievances", "subcategory": "Accident Prone Zones", "topic": "Accident", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Accident Prone Zones", "topic": "Black Spots", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": "Accident Prone Zones", "topic": "Road Safety Measures", "tonality": "Neutral & Negative"},
    {"category": "Grievances", "subcategory": "Miscellaneous", "topic": "Animal Menace", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": None, "topic": "Natural Calamities", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": None, "topic": "Protest", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": None, "topic": "Traffic Management", "tonality": "Neutral & Negative"},
    {"category": "Grievances", "subcategory": None, "topic": "Street Light Issue", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": None, "topic": "Deforestation", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": None, "topic": "Criminal Activity", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": None, "topic": "Rescue Operations", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": None, "topic": "Allegations on Nitin Gadkari", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": None, "topic": "Issues with Wayside Amenities", "tonality": "All Tonalities"},
    {"category": "Grievances", "subcategory": None, "topic": "Miscellaneous", "tonality": "All Tonalities"},
    {"category": "Projects and Infra", "subcategory": None, "topic": "Construction", "tonality": "All Tonalities"},
    {"category": "Projects and Infra", "subcategory": None, "topic": "Planning", "tonality": "All Tonalities"},
    {"category": "Projects and Infra", "subcategory": None, "topic": "Project Budget", "tonality": "All Tonalities"},
    {"category": "Projects and Infra", "subcategory": None, "topic": "Project Announcement", "tonality": "All Tonalities"},
    {"category": "Projects and Infra", "subcategory": None, "topic": "Multi-Modal Transport Hub (MMTH)", "tonality": "All Tonalities"},
    {"category": "Projects and Infra", "subcategory": None, "topic": "Highway Connectivity", "tonality": "All Tonalities"},
    {"category": "Projects and Infra", "subcategory": None, "topic": "Tunnel Construction", "tonality": "All Tonalities"},
    {"category": "Projects and Infra", "subcategory": None, "topic": "Road Fixtures", "tonality": "Only Positive"},
    {"category": "Projects and Infra", "subcategory": None, "topic": "Infrastructure Development", "tonality": "All Tonalities"},
    {"category": "Policies", "subcategory": None, "topic": "FASTag Annual Pass", "tonality": "All Tonalities"},
    {"category": "Policies", "subcategory": None, "topic": "PM RAHAT Scheme", "tonality": "All Tonalities"},
    {"category": "Policies", "subcategory": None, "topic": "CAFE-III Emission Norms", "tonality": "All Tonalities"},
    {"category": "Policies", "subcategory": None, "topic": "Motor Vehicle Bill", "tonality": "All Tonalities"},
    {"category": "Policies", "subcategory": None, "topic": "Toll Pricing", "tonality": "Only Positive"},
    {"category": "Policies", "subcategory": None, "topic": "Vehicle Scrapping Policy", "tonality": "All Tonalities"},
    {"category": "Policies", "subcategory": None, "topic": "BS-VI Emission Norms", "tonality": "All Tonalities"},
    {"category": "Policies", "subcategory": None, "topic": "PLI Scheme for Electric Vehicles", "tonality": "All Tonalities"},
    {"category": "Analysis Report", "subcategory": None, "topic": "Road Accident Data", "tonality": "All Tonalities"},
    {"category": "Analysis Report", "subcategory": None, "topic": "National Highway Data", "tonality": "All Tonalities"},
    {"category": "Rules Violation", "subcategory": None, "topic": "Law Enforcement", "tonality": "All Tonalities"},
    {"category": "Rules Violation", "subcategory": None, "topic": "Seatbelt Violation", "tonality": "All Tonalities"},
    {"category": "Rules Violation", "subcategory": None, "topic": "Helmet Violation", "tonality": "All Tonalities"},
    {"category": "Rules Violation", "subcategory": None, "topic": "Overspeeding", "tonality": "All Tonalities"},
    {"category": "Rules Violation", "subcategory": None, "topic": "Criminal Activity", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "Toll", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "Ethanol Blending", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "FASTag", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "Global Navigation Satellite System (GNSS)", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "EV (Related Topics)", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "Rajmarg Yatra App", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "CCTV Installation", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "Society of Indian Automobile Manufacturers (SIAM)", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "Advanced Traffic Management System (ATMS)", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "mParivahan App", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "Transport Sector", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "Traffic Surveillance System", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "Online Reputation Management (ORM)", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "Green Hydrogen Adoption", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "Electric Vehicle Adoption", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "electronic-Detailed Accident Report (e-DAR)", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "E20 Rollout Backfires", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "Electric Vehicle Charging Station", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "Advanced Driver Assistance Systems (ADAS)", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "Automated Testing Stations (ATS)", "tonality": "All Tonalities"},
    {"category": "Technology", "subcategory": None, "topic": "Anti-lock Braking System", "tonality": "All Tonalities"},
    {"category": "Irregularities", "subcategory": None, "topic": "Bribery", "tonality": "All Tonalities"},
    {"category": "Irregularities", "subcategory": None, "topic": "Corruption", "tonality": "All Tonalities"},
    {"category": "Irregularities", "subcategory": None, "topic": "Scam", "tonality": "All Tonalities"},
    {"category": "Irregularities", "subcategory": None, "topic": "Money laundering", "tonality": "All Tonalities"},
    {"category": "Irregularities", "subcategory": None, "topic": "NHAI Negligence", "tonality": "All Tonalities"}
]

print("Uploading master data to Supabase...")
response = supabase.table("taxonomy_entries").insert(initial_data).execute()
print("Successfully uploaded all taxonomy entries to your database!")
